import test from 'node:test';import assert from 'node:assert/strict';
import {freshState,buildMonth,consultationWeeks,validateSessions,validateBackup} from '../src/model.js';
const p=(category,start,end,days=[2])=>({category,start,end,days});
function state(schedule){const s=freshState();s.setups.fdtr.schedule=schedule;return s;}
test('six office hours become eight, with precise administrative gaps',()=>{const s=state([p('consultation','08:00','09:00'),p('class','09:00','11:00'),p('class','13:00','16:00')]),r=buildMonth(s,'fdtr','2026-09')[0];assert.equal(r.total,8);assert.deepEqual(r.sessions.filter(s=>s.generated).map(s=>[s.start,s.end]),[['11:00','12:00'],['16:00','17:00']]);assert.deepEqual(validateSessions(r.sessions,'fdtr'),[]);});
test('evening class is retained in addition to the full office day',()=>{const s=state([p('consultation','08:00','10:00'),p('class','13:30','15:30'),p('class','18:00','20:00')]),r=buildMonth(s,'fdtr','2026-09')[0];assert.equal(r.total,10);assert.equal(r.totals.others,4);assert.deepEqual(r.sessions.filter(s=>s.generated).map(s=>[s.start,s.end]),[['10:00','12:00'],['13:00','13:30'],['15:30','17:00']]);});
test('consultation-only workday receives six administrative hours; weekends and lunch are excluded',()=>{const s=state([p('consultation','08:00','10:00')]),rows=buildMonth(s,'fdtr','2026-09');assert.equal(rows[0].total,8);assert.equal(rows[0].totals.others,6);assert.equal(rows[4].total,0);assert.equal(rows[5].total,0);assert.ok(rows[0].sessions.every(s=>s.end<='12:00'||s.start>='13:00'));});
test('monthly exceptions override office fill; related half day preserves office work outside it',()=>{const s=state([p('consultation','08:00','10:00')]);s.months.fdtr['2026-09']={changes:{1:{kind:'Holiday',label:'HOLIDAY',sessions:[]},2:{kind:'Changed Schedule',label:'',sessions:[p('consultation','08:00','10:00')]},3:{kind:'Related activity',scope:'morning',description:'University activity',reference:'SO 123',label:'',sessions:[p('related','09:00','11:00')]}}};const rows=buildMonth(s,'fdtr','2026-09');assert.equal(rows[0].total,0);assert.equal(rows[1].total,2);assert.equal(rows[2].total,6);assert.deepEqual(rows[2].sessions.filter(s=>s.generated).map(s=>[s.start,s.end]),[['13:00','17:00']]);});
test('manual mode and customized working days/office times survive backup',()=>{const s=state([p('consultation','08:00','10:00')]);s.setups.fdtr.office.enabled=false;assert.equal(buildMonth(s,'fdtr','2026-09')[0].total,2);s.setups.fdtr.office={enabled:true,start:'07:00',end:'16:00',lunchStart:'12:00',lunchEnd:'13:00',days:[2],consultationTarget:8};assert.equal(buildMonth(s,'fdtr','2026-09')[0].total,8);assert.equal(buildMonth(s,'fdtr','2026-09')[1].total,0);assert.deepEqual(validateBackup(s),s);});
test('consultation checks include adjacent-month dates and flag exception weeks without adding hours',()=>{const s=state([p('consultation','08:00','10:00',[1,2,3,4,5])]);let weeks=consultationWeeks(s,'2026-09');assert.equal(weeks[0].from,'2026-08-31');assert.equal(weeks[0].hours,10);assert.equal(weeks.at(-1).to,'2026-10-04');s.months.fdtr['2026-09']={changes:{1:{kind:'Holiday',label:'HOLIDAY',sessions:[]}}};weeks=consultationWeeks(s,'2026-09');assert.equal(weeks[0].hours,8);assert.equal(weeks[0].short,true);assert.equal(weeks[0].exception,true);});
test('legacy backups acquire office options, invalid settings are rejected, DTR stays independent',()=>{const s=state([p('class','09:00','11:00')]);delete s.setups.fdtr.office;assert.equal(validateBackup(s).setups.fdtr.office.consultationTarget,10);assert.equal(buildMonth(s,'dtr','2026-09')[0].total,0);s.setups.fdtr.office={enabled:true,start:'17:00',end:'08:00',lunchStart:'12:00',lunchEnd:'13:00',days:[1],consultationTarget:10};assert.throws(()=>validateBackup(s));});

test('weekly target excludes lunch and consultation outside office working hours',()=>{const s=state([p('consultation','08:00','10:00',[1,2,3,4,5]),p('consultation','12:00','13:00',[1]),p('consultation','18:00','20:00',[2])]);const w=consultationWeeks(s,'2026-09')[0];assert.equal(w.hours,10);assert.equal(w.outsideHours,3);});
