import test from 'node:test';
import assert from 'node:assert/strict';
import {freshState,buildMonth,validateBackup,validateSessions,validateRelatedActivity} from '../src/model.js';
const state=()=>{const s=freshState();s.setups.fdtr.schedule=[{category:'consultation',start:'08:00',end:'10:00',days:[1,2,3,4,5]},{category:'others',start:'10:00',end:'12:00',days:[1,2,3,4,5]},{category:'class',start:'13:00',end:'19:00',days:[1,2,3,4,5]}];return s;};
const activity=(scope,sessions)=>({kind:'Related activity',scope,description:'Research Week',reference:'SO 123, series of 2026',label:'',sessions:sessions.map(([start,end])=>({category:'related',start,end}))});
function row(s,c){s.months.fdtr['2026-09']={changes:{1:c}};return buildMonth(s,'fdtr','2026-09')[0];}
test('full-day activities replace all recurring work and exclude lunch',()=>{const s=state(),r=row(s,activity('full',[['08:00','12:00'],['13:00','17:00']]));assert.equal(r.total,8);assert.equal(r.totals.related,8);assert.equal(r.totals.class,0);assert.equal(buildMonth(s,'fdtr','2026-10')[0].totals.related,0);assert.equal(s.setups.fdtr.schedule.length,3);});
test('half-day activity keeps the other half including evening teaching',()=>{const s=state(),r=row(s,activity('morning',[['08:00','12:00']]));assert.equal(r.totals.related,4);assert.equal(r.totals.class,6);assert.equal(r.totals.consultation,0);const a=row(s,activity('afternoon',[['13:00','17:00']]));assert.equal(a.totals.related,4);assert.equal(a.totals.consultation,2);assert.equal(a.totals.others,2);assert.equal(a.totals.class,0);});
test('custom periods trim overlapping work without double counting',()=>{const r=row(state(),activity('custom',[['09:00','11:00']]));assert.deepEqual(r.sessions.map(({category,start,end})=>({category,start,end})),[{category:'consultation',start:'08:00',end:'09:00'},{category:'related',start:'09:00',end:'11:00'},{category:'others',start:'11:00',end:'12:00'},{category:'class',start:'13:00',end:'19:00'}]);assert.equal(r.total,10);assert.deepEqual(validateSessions(r.sessions,'fdtr'),[]);});
test('activity data survives backup and never changes DTR',()=>{const s=state();s.setups.dtr.schedule=[{category:'lecture',start:'18:00',end:'20:00',days:[2]}];const before=buildMonth(s,'dtr','2026-09');row(s,activity('full',[['08:00','12:00'],['13:00','17:00']]));assert.deepEqual(validateBackup(s),s);assert.deepEqual(buildMonth(s,'dtr','2026-09'),before);delete s.months.fdtr['2026-09'].changes[1];assert.equal(buildMonth(s,'fdtr','2026-09')[0].total,10);});
test('rejects invalid half days, overlaps, missing descriptions, unsafe metadata and DTR activity records',()=>{assert.ok(validateRelatedActivity(activity('morning',[['13:00','17:00']])).length);assert.ok(validateRelatedActivity(activity('custom',[['09:00','11:00'],['10:00','12:00']])).length);const s=state(),c=activity('full',[['08:00','12:00']]);c.description='';row(s,c);assert.throws(()=>validateBackup(s));c.description='Research Week';c.reference='x'.repeat(101);assert.throws(()=>validateBackup(s));c.reference='SO 123';s.months.dtr['2026-09']=s.months.fdtr['2026-09'];assert.throws(()=>validateBackup(s));});
