import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(process.env.RUNTIME_MODULES+'/package.json'),{chromium}=require('playwright');
const browser=await chromium.launch({executablePath:'/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',headless:true});
try{const page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'}),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));await fs.mkdir('qa',{recursive:true});await page.goto(process.env.BASE_URL||'http://127.0.0.1:4173/repository-name/');
async function audit(name){if(process.env.AXE_PATH){await page.addScriptTag({path:process.env.AXE_PATH});const r=await page.evaluate(()=>axe.run({exclude:[['#document-preview']]},{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));results.push({name,violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});}}
async function overflow(name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' must reflow');}
await audit('home');await page.screenshot({path:'qa/interface-home-desktop.png',fullPage:true});await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(n=>n===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('main').evaluate(n=>n===document.activeElement),true);
await page.locator('[data-action="choose"][data-type="dtr"]').click();await audit('information');await page.getByLabel('Full name',{exact:true}).fill('TEST FACULTY');await page.getByRole('button',{name:'Continue',exact:true}).click();await audit('schedule');await page.locator('[data-action="add-schedule"]').click();assert.equal(await page.locator('dialog').getAttribute('aria-labelledby'),'dialog-title');await audit('schedule dialog');for(let i=0;i<18;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement.closest('dialog')),true,'Modal contains keyboard focus');}await page.keyboard.press('Escape');await page.waitForTimeout(50);assert.equal(await page.locator('[data-action="add-schedule"]').evaluate(n=>n===document.activeElement),true);
await page.locator('[data-action="add-schedule"]').click();await page.getByRole('button',{name:'Use this period'}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('In-charge name').fill('TEST HEAD');await page.getByRole('button',{name:'Finish Setup'}).click();await page.locator('#month').fill('2026-09');await audit('DTR month');await page.locator('[data-action="add-change"]').click();await page.locator('#change-kind').focus();await page.locator('#change-kind').selectOption('Changed Schedule');assert.equal(await page.locator('#change-kind').evaluate(n=>n===document.activeElement),true);await audit('monthly schedule change');await page.keyboard.press('Escape');
await page.locator('[data-action="preview"]').click();await page.locator('#reviewed:not([disabled])').waitFor();assert.ok(await page.locator('[data-action="pdf"]').isDisabled());assert.ok(await page.locator('#download-help').isVisible());await audit('preview controls');await page.locator('#reviewed').check();assert.equal(await page.locator('[data-action="pdf"]').isDisabled(),false);
await page.locator('[data-action="home"]').first().click();await page.evaluate(async()=>{const {freshState}=await import('./src/model.js'),s=freshState();s.profile.name='TEST FACULTY';s.profile.department='TEST DEPARTMENT';s.profile.designation='Faculty';s.setups.fdtr.ready=true;s.setups.fdtr.signatory='TEST HEAD';s.setups.fdtr.schedule=[{category:'consultation',start:'08:00',end:'10:00',days:[1,2,3,4,5]}];localStorage.setItem('dtr-fdtr-generator-v1',JSON.stringify(s));});await page.reload();await page.locator('[data-action="choose"][data-type="fdtr"]').click();await page.locator('#month').fill('2026-09');await audit('FDTR month');await page.screenshot({path:'qa/interface-fdtr-desktop.png',fullPage:true});
await page.locator('.supporting-review').first().locator('summary').click();await page.locator('[data-action="edit-office"]').click();assert.equal(await page.locator('.office-options').getAttribute('open')!==null,true);await audit('office arrangement');
await page.locator('[data-action="home"]').first().click();await page.setViewportSize({width:320,height:900});await overflow('320px home');await audit('mobile home');await page.screenshot({path:'qa/interface-home-mobile.png',fullPage:true});await page.locator('[data-action="choose"][data-type="fdtr"]').click();await overflow('320px month');await page.screenshot({path:'qa/interface-fdtr-mobile.png',fullPage:true});await page.locator('[data-action="add-change"]').click();await page.locator('#change-kind').selectOption('Related activity');await overflow('320px activity dialog');await audit('mobile activity dialog');await page.screenshot({path:'qa/interface-dialog-mobile.png'});await page.keyboard.press('Escape');
await page.setViewportSize({width:640,height:900});await page.evaluate(()=>{const sizes=[...document.querySelectorAll('body *')].filter(n=>!n.closest('#document-preview')).map(n=>[n,getComputedStyle(n).fontSize]);for(const [n,size] of sizes)n.style.fontSize=parseFloat(size)*2+'px';});await overflow('200% text month');await page.screenshot({path:'qa/interface-large-text.png',fullPage:true});
assert.deepEqual(errors,[]);await fs.writeFile('qa/interface-accessibility.json',JSON.stringify(results,null,2));const violations=results.flatMap(r=>r.violations.map(v=>({...v,page:r.name})));console.log(JSON.stringify({auditedPages:results.length,violations},null,2));assert.deepEqual(violations,[]);console.log('PASS: keyboard skip link, modal name and focus restoration, dynamic dialog focus, preview guidance/gating, 320px reflow, doubled text, reduced motion and accessibility audit.');
}finally{await browser.close();}
