export const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export const CATEGORIES={dtr:{lecture:'Lecture',laboratory:'Laboratory'},fdtr:{class:'Class',consultation:'Consultation',related:'Related activities',others:'Others (Adm., R&E)'}};
export const emptySetup=()=>({ready:false,term:'',from:'',to:'',schedule:[],signatory:'',official:'',regular:'',saturday:'',sunday:''});
export const freshState=()=>({version:1,profile:{name:'',department:'',signatureName:'',designation:''},setups:{dtr:emptySetup(),fdtr:emptySetup()},months:{dtr:{},fdtr:{}}});
export function daysInMonth(month){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Error('Choose a valid month.');let [y,m]=month.split('-').map(Number);if(y<1900||y>2200)throw Error('Choose a year from 1900 to 2200.');return new Date(Date.UTC(y,m,0)).getUTCDate();}
export function weekday(month,day){return new Date(`${month}-${String(day).padStart(2,'0')}T12:00:00Z`).getUTCDay();}
export function minutes(value){if(!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value||''))return NaN;let [h,m]=value.split(':').map(Number);return h*60+m;}
export const duration=s=>(minutes(s.end)-minutes(s.start))/60;
export function timeLabel(value){const m=minutes(value);return Number.isFinite(m)?`${Math.floor(m/60)%12||12}:${String(m%60).padStart(2,'0')} ${m>=720?'PM':'AM'}`:'';}
export function validateSessions(sessions,type){const errors=[];if(!Array.isArray(sessions))return ['Add a valid schedule.'];for(const s of sessions){if(!CATEGORIES[type][s.category])errors.push('Choose an activity for each time period.');if(!Number.isFinite(minutes(s.start))||!Number.isFinite(minutes(s.end)))errors.push('Enter both a start time and an end time.');else if(duration(s)<=0)errors.push('End time must be later than start time, on the same day.');if(type==='dtr'&&minutes(s.start)<720&&minutes(s.end)>720)errors.push('Split a period that crosses noon into morning and afternoon entries.');}
 const valid=sessions.filter(s=>duration(s)>0).sort((a,b)=>minutes(a.start)-minutes(b.start));for(let i=1;i<valid.length;i++)if(minutes(valid[i].start)<minutes(valid[i-1].end))errors.push('Two time periods overlap. Adjust their start or end times.');
 if(type==='dtr'){for(const half of [false,true])if(sessions.filter(s=>(minutes(s.start)>=720)===half).length>1)errors.push(`The DTR form has room for one ${half?'afternoon/evening':'morning'} period each day. It cannot show additional separate periods.`);}else for(const cat of Object.keys(CATEGORIES.fdtr))if(sessions.filter(s=>s.category===cat).length>3)errors.push(`The FDTR form has room for three ${CATEGORIES.fdtr[cat]} periods per day.`);
 return [...new Set(errors)];}
export function monthRecord(state,type,month){return state.months[type][month]||{changes:{}};}
export function buildMonth(state,type,month){const setup=state.setups[type],record=monthRecord(state,type,month),count=daysInMonth(month);return Array.from({length:count},(_,i)=>{const day=i+1,date=`${month}-${String(day).padStart(2,'0')}`,wd=weekday(month,day),active=(!setup.from||date>=setup.from)&&(!setup.to||date<=setup.to);let sessions=active?setup.schedule.filter(s=>s.days.includes(wd)).map(({days,...s})=>({...s})):[];let label=!sessions.length?(wd===6?'SATURDAY':wd===0?'SUNDAY':''):'';const change=record.changes[day];if(change){if(change.kind==='Changed Schedule'){sessions=change.sessions||[];label='';}else if(change.kind==='Additional Schedule'){sessions=[...sessions,...(change.sessions||[])];label='';}else {sessions=[];label=change.label||'';}}sessions.sort((a,b)=>minutes(a.start)-minutes(b.start));const totals=Object.fromEntries(Object.keys(CATEGORIES[type]).map(k=>[k,sessions.filter(s=>s.category===k).reduce((n,s)=>n+duration(s),0)]));return {day,date,weekday:wd,sessions,label,change,totals,total:sessions.reduce((n,s)=>n+duration(s),0)};});}
export function validateMonth(state,type,month){const errors=[],setup=state.setups[type];if(!state.profile.name.trim())errors.push({text:'Enter your name.',fix:'info'});if(type==='fdtr'&&(!state.profile.department.trim()||!state.profile.designation.trim()))errors.push({text:'Enter your department and designation.',fix:'info'});if(!setup.signatory.trim())errors.push({text:'Enter the name of your signatory.',fix:'signatory'});if(!setup.schedule.length)errors.push({text:'Add your usual schedule.',fix:'schedule'});if(setup.from&&setup.to&&setup.from>setup.to)errors.push({text:'Your schedule ends before it begins.',fix:'schedule'});const first=`${month}-01`,last=`${month}-${daysInMonth(month)}`;if((setup.from&&setup.from>last)||(setup.to&&setup.to<first))errors.push({text:'Your saved schedule does not cover this month. Review its dates.',fix:'schedule'});for(const row of buildMonth(state,type,month)){for(const text of validateSessions(row.sessions,type))errors.push({text:`Day ${row.day}: ${text}`,fix:'day',day:row.day});if(row.change&&['Leave','No Class','Other'].includes(row.change.kind)&&!row.change.blank&&!row.label.trim())errors.push({text:`Day ${row.day}: enter the wording required on the form.`,fix:'day',day:row.day});}return errors;}
export function validateBackup(x){if(!x||x.version!==1||!x.profile||!x.setups||!x.months)throw Error('This file is not a DTR & FDTR backup.');const result=freshState();for(const k of Object.keys(result.profile)){if(typeof x.profile[k]!=='string'||x.profile[k].length>100)throw Error('Some personal information in this backup is invalid.');result.profile[k]=x.profile[k];}for(const type of ['dtr','fdtr']){const s=x.setups[type];if(!s||!Array.isArray(s.schedule)||s.schedule.length>100||typeof s.ready!=='boolean')throw Error('The saved schedule is invalid.');for(const k of ['term','from','to','signatory','official','regular','saturday','sunday']){if(typeof s[k]!=='string'||s[k].length>150)throw Error('The saved settings are invalid.');}for(const k of ['from','to'])if(s[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(s[k]))throw Error('The saved schedule dates are invalid.');for(const session of s.schedule){if(!Array.isArray(session.days)||!session.days.length||session.days.some(d=>!Number.isInteger(d)||d<0||d>6)||validateSessions([session],type).length)throw Error('The saved time periods are invalid.');}result.setups[type]=structuredClone(s);const records=x.months[type];if(!records||typeof records!=='object'||Array.isArray(records))throw Error('The saved months are invalid.');for(const [month,record] of Object.entries(records)){const count=daysInMonth(month);if(!record?.changes||typeof record.changes!=='object')throw Error('The saved monthly changes are invalid.');const clean={changes:{}};for(const [day,c] of Object.entries(record.changes)){if(!/^\d+$/.test(day)||+day<1||+day>count||!['Holiday','Leave','No Class','Changed Schedule','Additional Schedule','Other'].includes(c.kind)||typeof c.label!=='string'||c.label.length>36||!Array.isArray(c.sessions)||c.sessions.length>12||validateSessions(c.sessions,type).length)throw Error('A saved monthly change is invalid.');clean.changes[day]={kind:c.kind,label:c.label,...(c.blank===true?{blank:true}:{}),sessions:c.sessions.map(s=>({category:s.category,start:s.start,end:s.end}))};}result.months[type][month]=clean;}}
return result;}
